services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.services
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: fastapi_backend
    env_file:
      - ./app/backend/.env
    volumes:
      - ./app/backend:/project/app/backend
    restart: unless-stopped
    expose:
      - "8000"  # Only accessible to other containers

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: frontend_app
    volumes:
      - ./app/frontend:/project/app/frontend
      - /project/app/frontend/node_modules
    restart: unless-stopped
    env_file:
      - ./app/frontend/.env
    expose:
      - "5173"  # Only accessible to other containers

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: