services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.services
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: fastapi_backend
    volumes:
      - ./app/backend/alembic:/project/app/backend/alembic
      - ./challenges/deployment:/project/challenges/deployment
    env_file:
      - ./app/backend/.env
    restart: unless-stopped
    expose:
      - "8000"  # Only accessible to other containers

  migrate:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: alembic_migrate
    env_file:
      - ./app/backend/.env
    depends_on:
      - postgres
    command: python -m alembic -c /project/app/backend/alembic.ini upgrade head

  create-admin:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: create_admin
    env_file:
      - ./app/backend/.env
    depends_on:
      - postgres
    command: python -m app.backend.scripts.manage --email admin@example.com


  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: frontend_app
    expose:
      - "80"
    restart: unless-stopped
    env_file:
      - ./app/frontend/.env

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "8025:8025"   # Web UI
  #     - "1025:1025"   # SMTP
  
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"


volumes:
  postgres_data: