version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: fastapi_backend
    env_file:
      - ./app/backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/project/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    volumes:
      # Mount source for hot-reloading
      - ./app/frontend:/project/app/frontend
      - /project/app/frontend/node_modules
    restart: unless-stopped
    # specific environment variables for frontend can go here
    env_file:
      - ./app/frontend/.env.development