apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pwndepot-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubosis/pwndepot.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true      # Delete resources if deleted from Git
      selfHeal: true   # Fix the cluster if someone manually deletes a pod
    syncOptions:
      - CreateNamespace=true