apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: challenge-rewrite-sse
  namespace: default
spec:
  # Middleware for rewriting for /challenge
  replacePathRegex:
    regex: ^/challenge/i/([^/]+)(/.*)?$
    replacement: /api/v1/challenges/i/$1$2

  # Middleware for SSE (Server-Sent Events)
