# k8s/challenge-rewrite-middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: challenge-strip-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - "/challenge"