apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoip-pv
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: geoip-hostpath
  hostPath:
    path: /var/lib/pwndepot/geoip
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoip-pvc
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Mi
  storageClassName: geoip-hostpath