apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure   
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd,default-redirect-to-www@kubernetescrd,default-challenge-strip-prefix@kubernetescrd
spec:
  rules:
  - host: pwndep0t.com
    http:
      paths:
      - path: /challenge
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: www.pwndep0t.com
    http:
      paths:
      - path: /challenge
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000